### PR TITLE
Build in postinstall, so package can be used from npm.

### PR DESCRIPTION
**Pull request by CezaryDanielNowak**

### CODE REVIEW

**Comment by eternalsky** [comment]
the component will be built before publishing in our publishing scirpt `npm run pub`, so the component does not need postinstall

**Comment by CezaryDanielNowak** [comment]
@eternalsky This is fix for: 
`npm install --save uxcore-table`
When doing `import Table from 'uxcore-table'` It was throwing an error about  `build/index.js` not found.

Did I do something wrong?

**Comment by eternalsky** [comment]
which version is installed ? the build folder will be generated in pub srcipt，so this problem should not exist.

**Comment by CezaryDanielNowak** [comment]
Hmm you're right, the problem was on me. uxcore-table@4.1.1 works smooth :-)

ps. uxcore-table is so nice, much better than react-table, griddle or react-virtualized. It's weird it has only 37 stars.

**Comment by eternalsky** [comment]
@CezaryDanielNowak Thanks for your appreciation. Promotion is a difficult work and we are now working on it. if you think uxcore-table is good, please recommend your friends to use :-)

**Pull request closed without merging**
